### PR TITLE
Bigsur 11.2 oc 0.6.6

### PR DESCRIPTION
**Pull request by vincent-chang-rightfighter**
- Update Opencore 0.6.6 ( update Opencore.efi , OpenRuntime.efi , Opencanopy.efi  )
- Delete bootstrap ( Opencore 0.6.6 No longer need )
- Update Kext
- Drive HD630 use AAPL,ig-platform-id 00001B59  
fix_hd630
Only for macos 
Windows 10 -> bosd
Ubuntu no test

### CODE REVIEW

**Comment by jbwharris** [comment]
I'm curious about changing the platform id? I found that the ID had in there was the only one that worked with my machine to keep the laptop screen from flickering. I'll have to test if that's in fact resolved in 0.6.6, as it's been a few versions since I last tried it.

**Comment by vincent-chang-rightfighter** [comment]
I Just follow WhateverGreen guide

The guide recommend Laptop framebuffers that use 591B0000 

Fix Laptop Kabylake  HD 630 PlatformId and framebuffers

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-uhd-graphics-610-650-kaby-lake-and-amber-lake-y-processors

I Just notice that 

ID: 591C0005, STOLEN: 57 MB, FBMEM: 0 bytes, VRAM: 1536 MB, Flags: 0x00A30702
TOTAL STOLEN: 58 MB, TOTAL CURSOR: 1 MB (1572864 bytes), MAX STOLEN: 172 MB, MAX OVERALL: 173 MB (181940224 bytes)
Model name: Intel UHD Graphics 617
Camellia: CamelliaV3 (3), Freq: 1388 Hz, FreqMax: 1388 Hz
Mobile: 1, PipeCount: 3, PortCount: 3, FBMemoryCount: 3
[0] busId: 0x00, pipe: 8, type: 0x00000002, flags: 0x00000098 - ConnectorLVDS
[1] busId: 0x05, pipe: 9, type: 0x00000400, flags: 0x000003C7 - ConnectorDP
[2] busId: 0x04, pipe: 10, type: 0x00000400, flags: 0x000003C7 - ConnectorDP
00000800 02000000 98000000
01050900 00040000 C7030000
02040A00 00040000 C7030000


ID: 591B0000, STOLEN: 38 MB, FBMEM: 21 MB, VRAM: 1536 MB, Flags: 0x0000130B
TOTAL STOLEN: 39 MB, TOTAL CURSOR: 1 MB (1572864 bytes), MAX STOLEN: 136 MB, MAX OVERALL: 137 MB (144191488 bytes)
Model name: Intel HD Graphics KBL CRB
Camellia: CamelliaDisabled (0), Freq: 1388 Hz, FreqMax: 1388 Hz
Mobile: 1, PipeCount: 3, PortCount: 3, FBMemoryCount: 3
[0] busId: 0x00, pipe: 8, type: 0x00000002, flags: 0x00000098 - ConnectorLVDS
[2] busId: 0x04, pipe: 10, type: 0x00000800, flags: 0x00000187 - ConnectorHDMI
[3] busId: 0x06, pipe: 10, type: 0x00000400, flags: 0x00000187 - ConnectorDP
00000800 02000000 98000000
02040A00 00080000 87010000
03060A00 00040000 87010000

**Comment by rlindsberg** [comment]
Yes, by best practices should 591B0000 be used to enable Intel graphics hardware acceleration. But in this case it's causing issues for @jbwharris

**Comment by jbwharris** [comment]
@vincent-chang-rightfighter What's weird is it was in the OpenCore guide at some point previously it was in there. I struggled for a very long time trying to get the recommended platform-ids to work properly, then discovered with my setup that 05001c59 was the missing piece. My machine does sleep wake, no flicker, no crashing and can drive external monitors on HDMI and DP ports. My last reboot cycle was over 10 days and I'm currently 6 days into my current one. So despite what the guide says, I'm saying that's the platform-id that works best for this particular laptop. I'm not sure if you use dark mode on your machine, but the problem I was experiencing was a flicker in the darks on the LVDS(laptop) screen, while the HDMI was fine. I'll give the default a try and see if maybe something changed in the last 8 months with OpenCore to make the default work.

**Comment by rlindsberg** [comment]
As we discussed here https://github.com/rlindsberg/OS-X-on-MSI-GL62m-7REX/issues/17 , the only thing missed without proper platform-id is hardware acceleration for HEVC encoded videos. Without hardware acceleration, the CPU will have to do the tasks that could be parallel-computed by the integrated GPU (Intel HD630). This means watching Youtube videos would be slower and less energy efficient.

**Comment by rlindsberg** [comment]
@jbwharris 
Just curious, would you try and change the ig-platform-id to 00001B59 **and** device-id to 16590000 and test if the screen flickers?

**Comment by jbwharris** [comment]
@vincent-chang-rightfighter @rlindsberg I just changed it and I'm not seeing the flickering issues I've experienced before, which is great. I always thought it was an OpenCore thing more than anything, but just because it used to work with Clover. I didn't upgrade to 0.6.6 or 11.2 yet, so I'll run it for a bit and see if I notice any weirdness. I know previously sometimes it would be fine on boot, but then subsequent sleep wakes it would reappear.

**Comment by rlindsberg** [comment]
> I just changed it and I'm not seeing the flickering issues I've experienced before, which is great. I always thought it was an OpenCore thing more than anything, but just because it used to work with Clover.

What happens if you use device-id 16190000? Does the screen flicker?

**Comment by jbwharris** [comment]
I'm still not sure if I'm convinced on the platform ID. I keep finding that I'll wake up in the morning and the keyboard is lit up instead of being in a deep sleep. It's happened probably 3 of the 4 nights since I changed it. And I've seen it stay on standby with the keyboard lit up in instances it probably should have gone to deep sleep. It's still not crashing which is great though.

**Comment by rlindsberg** [comment]
> I'm still not sure if I'm convinced on the platform ID. I keep finding that I'll wake up in the morning and the keyboard is lit up instead of being in a deep sleep. It's happened probably 3 of the 4 nights since I changed it. And I've seen it stay on standby with the keyboard lit up in instances it probably should have gone to deep sleep. It's still not crashing which is great though.

That maybe means that the macOS native power management is working for the first time!
Can you check the Energy Saver menu in Settings and post a screenshot here?

**Comment by jbwharris** [comment]
image 

I'm not really sure what to make from this. I made the change Monday night. I don't get why it would be saying the screen was off given it's on probably on 8-12 hours a day. So those Thur/Fri/Sat stats seem accurate, but not being on at all doesn't make sense.

**Comment by rlindsberg** [comment]
Skærmbillede 2021-02-13 kl  12 44 56

Please enter this menu and attach a screenshot of it.

**Comment by rlindsberg** [comment]
My bad, forgot you are using Big Sur right now.

Please click the tab Power Adapter to the left and attach a screenshot.

**Comment by rlindsberg** [comment]
I am not making any statement about the correct platform-id is better. Obviously you should use the one that works for you. But I just wanted to figure out the root cause of the screen flickering problem and the not sleeping problem.

You know, people doing hackintoshes are mostly nerds about technology...

**Comment by jbwharris** [comment]
image
 Here's the power adapter screen

**Comment by jbwharris** [comment]
image
Power adapter screen

**Comment by rlindsberg** [comment]
Please disable "Wake for network access" and test if deep sleep works.

**Comment by jbwharris** [comment]
It does go to deep sleep, though I will have to test over the next day to see if it has an effect on going to sleep after a time and staying asleep overnight. I'm curious if Power Nap might work, as I'd love to be able to run that stuff overnight. I know I turned it off at some point previously when dealing with sleep issues.

**Comment by rlindsberg** [comment]
> It does go to deep sleep, though I will have to test over the next day to see if it has an effect on going to sleep after a time and staying asleep overnight.

Yes, please do.

> I'm curious if Power Nap might work

Power nap is just sleep, but the computer will wake up by itself from time to time to check emails, for example. Is that what you wanted to do?
If you see this option, it means that the native power management is working. It could of course be verified using more accurate method like IORegistryExplorer.

**Comment by jbwharris** [comment]
Yeah, I would love if backup and some Automator stuff ran overnight for me.

**Pull request closed without merging**
